services:
  # PostgreSQL
  postgres-db:
    container_name: tienda-db_postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - tienda-db-data:/var/lib/postgresql/data
      - ./database/tienda.sql:/docker-entrypoint-initdb.d/tienda.sql
    networks:
      - tienda-network

  # MongoDB
  mongo-db:
    container_name: tienda-db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - tienda-db-mongo:/data/db
      - ./database/tienda.js:/docker-entrypoint-initdb.d/tienda.js
    networks:
      - tienda-network

networks:
  tienda-network:
    driver: bridge

volumes:
  tienda-db-data:
  tienda-db-mongo: